---
params: 
  id: "zilt"
  paragraaf: "inleiding"
header-includes: \usepackage{xcolor}
output:
  pdf_document
bibliography:
  - voorbeeld_bibliografie.bib
---

```{r setup, include=FALSE}
library(rprojroot)
library(tidyverse)
library(n2khab)
knitr::opts_chunk$set(echo = TRUE)
source(find_root_file(
    "source/r/get_habitats.r",
    criterion = has_file("EU_rapportage_habitats.Rproj")))
hab <- habitattypes %>%
  filter(typelevel == "main_type") %>%
  filter(!(main_type %in% c('9110', '9150', '1110') |
             str_detect(main_type, "rbb")),
         id == params$id) %>%
  select(main_type, `type_name`,
         `type_shortname`) 
```

# Tekstopmaak

In ieder van de documenten schrijf je een stuk tekst dat bij het desbetreffende hoofdstuk, de figuur of tabel hoort. 

Indien je tekst in *italics* wil schrijven, doe je dat door voor en na dit stuk tekst een '\*'asterisk'\*' te zetten. Voor **bold** tekst, zet je twee '\*\*'asterisken'\*\*' voor en na je stuk tekst dat je vet gedrukt wil zien in het rapport.

# Refereren naar tabellen en figuren

Je kan ook refereren naar de verschillende tabellen en figuren in het originele document, dat doe je zo:

- Schrijf tabel \\@ref(tab:`r params$id`-habitattypen) om te refereren naar de tabel met de verschillende habitattypes en habitatname.
- Schrijf figuur \\@ref(fig:`r params$id`-areaal-verspreiding) om te refereren naar de figuur met kaart(en) van het areaal en de verspreiding.
- Schrijf tabel \\@ref(tab:`r params$id`-areaal-tabel) om te refereren naar de tabel met trend, FRR en eindconclusie(s) voor het areaal.
- Schrijf figuur \\@ref(fig:`r params$id`-oppervlakte-bars) om te refereren naar de bar chart figuren.
- Schrijf tabel \\@ref(tab:`r params$id`-oppervlakte) om te refereren naar de tabel beste oppervlaktewaarde (totaal voor Vlaanderen), aandeel in het SBZ-H-netwerk, trendrichting, relatie tot de referentieoppervlakte voor regionaal gunstige toestand (FRA) en eindconclusie voor habitatoppervlakte
- Schrijf figuur \\@ref(fig:`r params$id`-aandeelGunstigeStaat) om te refereren naar de figuur met error bars voor het oppervlakteaandeel in gunstige staat in Vlaanderen (habitattypes op de y-as).
- Schrijf tabel \\@ref(tab:`r params$id`-specifiekestructuren-soorten-samenhang) om te refereren naar de tabel met een overzicht van de indicatorscores van de criteria ‘Typische soorten’ en ‘Ruimtelijke samenhang’, met vermelding van hun belang.
- Schrijf tabel \\@ref(tab:`r params$id`-specifiekestructuren-eindoordeel) om te refereren naar de tabel met eindoordeel en trend voor specifieke structuren en functies.
- Schrijf figuur \\@ref(fig:lsvifiguur**XXXX**) om te refereren naar de LSVI figuur voor habitat nummer **XXXX** (mogelijke opties voor **XXXX** zijn `r as.character(hab$main_type)`). Mogelijks is er niet voor ieder habitattype een figuur voor het oppervlakteaandeel in gunstige staat per indicator (bij gebrek aan data).
- Schrijf tabel \\@ref(tab:`r params$id`-drukken-bedreigingen) om te refereren naar de tabel met drukken en bedreigingen.
- Schrijf tabel \\@ref(tab:`r params$id`-ihm) om te refereren naar de tabel met instandhoudingsmaatregelen.
- Schrijf tabel \\@ref(tab:`r params$id`-toekomst) om te refereren naar de tabel met toekomstperspectieven.
- Schrijf tabel \\@ref(tab:`r params$id`-conclusie) om te refereren naar de samenvattende tabel van de conclusies per criterium en einduitspraak over de algemene toestand en trend van de instandhouding per habitattype.

# Refereren naar de literatuur

Om te kunnen refereren naar de literatuur, moet er eerst een bibliografie opgebouwd worden.
We raden aan om enkel werken op te nemen in de bibliografie waarnaar in de tekst gerefereerd wordt.
Zodra een werk is opgenomen in de bibliografie kan je het werk citeren door het label te gebruiken.

## Bibliografie opmaken

We vragen ol je bibliografie in BibTex formaat aan te leveren. 

Zotero gebruikers volgen de volgende stappen:

- Selecteer alle items die je in je bibligrafie wil opnemen.
- Klik rechts op de geselecteerde bestanden en kies "Gesecteerde items exporteren...".
- Kies bibtex formaat en sla je bibliografie lokaal op als , bijvoorbeeld, *`r params$id`-refs.bibtex*.

Voor EndNote gebruikers raden we aan om de geselecteerde referenties op de volgende manier te exporteren in BibTex format:

- Edit -> Output Styles -> Open de style manager enkies BibTex export entry.
- Zorg er ook voor dat BibTex Export aangevinkt is in het menu Edit -> Output styles
- Kies File -> Export, selecteer "Text file" al bestandsformaat in het dropdown menu en bewaar het bestand als, bijvoorbeeld, *`r params$id`-refs.bibtex*.

Vervolgens laadt je je .bibtex bestand(en) vervolgens op in [deze Google drive map](https://drive.google.com/drive/folders/1iPCilJi0VX6qtMduInqvmR186N6YGffw).

Meer informatie over citaties in een RMarkDown bestand vindt je op onze [tutorials pagina](https://inbo.github.io/tutorials/tutorials/r_citations_markdown/).

## Literatuur citeren in je tekst

Ieder werk in je bibliografie zal een label gekregen hebben. Dat label vind je terug in je .bibtex file. Je kan je .bibtex file openen in kladblok of Rstudio.

Een .bibtex element voor het boek van Agresti ziet er uit zoals hieronder weergegeven. Het label is dan `agresti_categorical_2012`.

```{css echo = TRUE, eval = FALSE}
@book{agresti_categorical_2012,
	title = {Categorical {Data} {Analysis}},
	isbn = {978-0-470-46363-5},
	language = {en},
	publisher = {John Wiley \& Sons},
	author = {Agresti, Alan},
	month = dec,
	year = {2012},
	keywords = {Computers / Data Science / Data Analytics, Mathematics /
	General, Mathematics / Probability \& Statistics / General, Mathematics /
	Probability \& Statistics / Multivariate Analysis, Mathematics / 
	Probability \& Statistics / Stochastic Processes},
}
```

Met behulp van de labels kan je nu het boek citeren. 
Schrijf `@agresti_categorical_2012` om zonder haakjes te citeren:

@agresti_categorical_2012 is een boek over categorische data analyse.

Schrijf `[@agresti_categorical_2012]` om met haakjes te citeren:

Er bestaan heel wat boeken over categorische data analyse [@agresti_categorical_2012].


# Bibliografie
